// Repertorios originales de Pedro Poitevin, conservados sin cambios.
export const repertoires = {
  "en": [
    [
      "No omen in a call, it's still a sign,",
      "No omen of one dragon, evil sign,",
      "No omen old as sore, no evil sign,",
      "No omen as a sore, no evil sign,",
      "No omen in a caw as level sign,",
      "No omen. Old eye level, still. A sign,",
      "No omen, I pull, ever stray, a sign,",
      "No omen, I pull air, ear even, sign",
      "No omen in a clam, red, level sign,",
      "No omen in a claro, manward sign,"
    ],
    [
      "a faraway, reviled delivery.",
      "a faraway raid, a delivery.",
      "a faraway raid, spool, delivery.",
      "a faraway raid's flow, delivery.",
      "a faraway raid's drab delivery.",
      "a faraway raid, won delivery.",
      "a faraway raid's yaw, delivery.",
      "a faraway raid's doom delivery.",
      "a faraway raid's mood, delivery.",
      "a faraway raid, war, delivery."
    ],
    [
      "Assay a war, a flavor of no wine,",
      "Assay a waste, gnome, devil, era, wine,",
      "Assay a way arts air as rotor's tine,",
      "Assay a way arts air, a level mine,",
      "Assay a way arts air, a level's tine,",
      "Assay a way arts air, a tenet's tine,",
      "Assay a way arts air as tenet's tine,",
      "Assay a way arts air, a rotor's tine,",
      "Assay a way arts air, as radar's tine,",
      "Assay a way arts air, a radar's tine,"
    ],
    [
      "risen urn, inward gaze, no laniary.",
      "risen urn, inward muse, no laniary.",
      "risen urn, inward dirge, no laniary.",
      "risen urn, inward page, no laniary.",
      "risen urn, inward name, no laniary.",
      "risen urn, inward, rife, no laniary.",
      "risen urn, inward tune, no laniary.",
      "risen urn, inward mare, no laniary.",
      "risen urn, inward pile, no laniary.",
      "risen urn, inward mire, no laniary."
    ],
    [
      "Beryl, one rock, core mass laid rotative,",
      "Beryl, one rock, core laps laid rotative,",
      "Beryl, one rock, core pods laid rotative,",
      "Beryl, one rock, core nods laid rotative,",
      "Beryl, one rock, core nil laid rotative,",
      "Beryl, one rock, core dam laid rotative,",
      "Beryl, one rock, core laws laid rotative,",
      "Beryl, one rock, core law laid rotative,",
      "Beryl, one rock, core firs laid rotative,",
      "Beryl, one rock, core fir laid rotative,"
    ],
    [
      "layer gyrator, never ever apt,",
      "layer grammar, gaps, argot's liar, apt,",
      "layer gyrator, divan, ever apt,",
      "layer gyrator's timer, ever apt,",
      "layer gyrator, liver, ever apt,",
      "layer gyrator, redder, ever apt,",
      "layer gyrator's partner ever apt,",
      "layer grammar got duals, ever apt,",
      "layer gyrator, no duals, ever apt,",
      "layer gyrator, damn warder ever apt,"
    ],
    [
      "a gift, part saved, I ride, yaw. Still, I give",
      "a gift, part saved, I side, yaw. Still, I give",
      "a gift, part lobed, I ride, yaw. Still, I give",
      "a gift, part lobed, I side, yaw. Still, I give",
      "a gift, part caped, I ride, yaw. Still, I give",
      "a gift, part caped, I side, yaw. Still, I give",
      "a gift, part saved, I bide, yaw. Still, I give",
      "a gift, part lobed, I bide, yaw. Still, I give",
      "a gift, part caped, I bide, yaw. Still, I give",
      "a gift, part saved, I hide, yaw. Still, I give"
    ],
    [
      "no one vigil. Lit, swayed, I ride, vast, rapt.",
      "no one vigil. Lit, swayed, I side, vast, rapt.",
      "no one vigil. Lit, swayed, I ride, bolt, rapt.",
      "no one vigil. Lit, swayed, I side, bolt, rapt.",
      "no one vigil. Lit, swayed, I ride pact, rapt.",
      "no one vigil. Lit, swayed, I side pact, rapt.",
      "no one vigil. Lit, swayed, I bide, vast, rapt.",
      "no one vigil. Lit, swayed, I bide, bolt, rapt.",
      "no one vigil. Lit, swayed, I bide pact, rapt.",
      "no one vigil. Lit, swayed, I hide, vast, rapt."
    ],
    [
      "Fig at par, ever even, rotary, grey,",
      "Fig at par ails to grasp a grammar, grey,",
      "Fig at par, even, avid, rotary, grey,",
      "Fig at par ever emits rotary grey,",
      "Fig at par, ever evil, rotary, grey,",
      "Fig at par, eve redder, rotary, grey,",
      "Fig at par, ever entraps rotary grey,",
      "Fig at par, eve's laud to grammar grey,",
      "Fig at par, eve's laud on rotary grey,",
      "Fig at par, eve redrawn, mad rotary grey,"
    ],
    [
      "a levitator dial's same rock core.",
      "a levitator dial's pale rock core.",
      "a levitator dial's dope rock core.",
      "a levitator dial's done rock core.",
      "a levitator dial, line, rock core.",
      "a levitator dial made rock core.",
      "a levitator dial's wale, rock core.",
      "a levitator dial, wale, rock core.",
      "a levitator dial's rife rock core.",
      "a levitator dial, rife rock core."
    ],
    [
      "No lyre by rain, a lone zag drawn in rune.",
      "No lyre by rain, a lone sum drawn in rune.",
      "No lyre by rain, a lone grid drawn in rune.",
      "No lyre by rain, a lone gap drawn in rune.",
      "No lyre by rain, a lone man drawn in rune.",
      "No lyre by rain, a lone fir drawn in rune.",
      "No lyre by rain, a lone nut drawn in rune.",
      "No lyre by rain, a lone ram drawn in rune.",
      "No lyre by rain, a lone lip drawn in rune.",
      "No lyre by rain, a lone rim drawn in rune."
    ],
    [
      "Siren I won for oval far away:",
      "Siren, I ware; live demon gets a way:",
      "Siren, its rotors' aria stray away:",
      "Siren, I'm level, aria stray away:",
      "Siren, its level aria stray away:",
      "Siren, its tenet aria stray away:",
      "Siren, its tenet's aria stray away:",
      "Siren, its rotor—aria stray away:",
      "Siren, its radar's aria stray away:",
      "Siren, its radar–aria stray away:"
    ],
    [
      "Assay reviled delivery, a war;",
      "Assay, reviled, a diary, a war;",
      "Assay, reviled loop's diary, a war;",
      "Assay, reviled Wolf's diary, a war;",
      "Assay reviled bard's diary, a war;",
      "Assay, reviled now, diary, a war;",
      "Assay reviled ways' diary, a war;",
      "Assay, reviled, mood's diary, a war;",
      "Assay, reviled doom's diary, a war;",
      "Assay, reviled, raw diary, a war;"
    ],
    [
      "a fang is all: it's still a canine moon.",
      "a fang is live, no garden of one moon.",
      "a fang is live on Eros, sad lone moon.",
      "a fang is live on Eros, a sane moon.",
      "a fang is level saw, a canine moon.",
      "a fang, is all: its level eyed lone moon.",
      "a fang, I say! Arts revel, lupine moon.",
      "a fang is never aerial lupine moon.",
      "a fang is level, dermal, canine moon.",
      "a fang is drawn: amoral, canine moon."
    ]
  ],
  "es": [
    [
      "Amor banal, la nueva levedad,",
      "Amor, alegre vida, levedad,",
      "Amor alegre -¡vaya levedad!-,",
      "Amor, balsa de lisa levedad,",
      "Amor, alegre veta, levedad,",
      "Amor baldío, a sola levedad,",
      "Amor, barra banal, la levedad,",
      "Amor barómetro, petral, edad,",
      "Amor banal, la viva levedad,",
      "Amor alegre ve la levedad,"
    ],
    [
      "y a modosita, a leve risa y ola,",
      "y a modo sodomita, a leve rola,",
      "y a modo sed, a leve risa y ola,",
      "y a modo sed, a birra, a leve rola,",
      "y a modo sed, a mora, a leve rola,",
      "y a modosita, a birra, a leve rola,",
      "y a modosita, a diva, leve rola,",
      "y a modo sedación, a rap, a sola,",
      "y a modoso mocete leve rola,",
      "y a modo sodomita y a más ola,"
    ],
    [
      "fácil panal payar a su maldad,",
      "fácil paz a la sima -a su maldad-,",
      "fácil paz a revés a su maldad,",
      "fácil panal payar a la maldad,",
      "fácil paz a la sima -a la maldad-,",
      "fácil paz a revés, a la maldad,",
      "fácil palo -golosa su maldad-,",
      "fácil palo -golosa la maldad-,",
      "fácil panal payar a mi maldad,",
      "fácil palo -golosa mi maldad-,"
    ],
    [
      "revelé ver soneto, no la cola.",
      "revelé verso neto, no la cola.",
      "revelé ver soneto, rola, cola.",
      "revelé verso neto, rola, cola.",
      "revelé verde sale de la cola.",
      "revelé verde sale de la cola.",
      "revelé verde si me dé la cola.",
      "revelé verde si me dé la cola.",
      "revelé verde sí, mi sima, cola.",
      "revelé verde sí, mi sima, cola."
    ],
    [
      "La yací, risa y -ojo- sola, frágil,",
      "La yací, risa y ojos ola, frágil,",
      "La yací, risa y ojos, ola frágil,",
      "La yací, risa y -ojo- sola, frágil,",
      "La yací, risa y ojos ola, frágil,",
      "La yací, risa y ojos, ola frágil,",
      "La yací, risa y alas, ola frágil,",
      "La yací, risa y alas, ola frágil,",
      "La yací, risa y ala, sola, frágil,",
      "La yací, risa y -¡ala!- sola, frágil,"
    ],
    [
      "y el edén, o por prisas, otro corto",
      "y el edén, o por prisas, otro corto",
      "y el edén -¡opa y risas!-. Otro corto",
      "y el edén, -¡opa y risas!-. Otro corto",
      "y el edén, o por prisas, otro corto",
      "y el edén, -¡opa y risas!-. Otro corto",
      "y el edén, o por prisas, otro corto",
      "y el edén, o por prisas, otro corto",
      "y el edén, o por prisas, otro corto",
      "y el edén, -¡opa y risas!-. Otro corto"
    ],
    [
      "a otro le di. ¡Si soy, será más ágil!",
      "a otro le di. ¡Si soy, será más ágil!",
      "a otro le doy. Y ya será más ágil.",
      "a otro le doy. Y ya será más ágil.",
      "a otro le doy y ya. ¡Será más ágil!",
      "a otro le doy y ya. ¡Será más ágil!",
      "a otro le doy y ya. ¿Será más ágil?",
      "a otro le doy y ya. ¿Será más ágil?",
      "a otro le doy y -¡Alá!- ¿será más ágil?",
      "a otro le doy y -¡Alá!- ¿será más ágil?"
    ],
    [
      "- ¿Ligás a mares? - ¿Yo? ¡Sí, sí, del orto!",
      "- ¿Ligás a mares? - ¡Yo sí, sí, del orto!",
      "- ¿Ligás a mares? - Ay, ¿y yo? ¡Del orto!",
      "- ¿Ligás a mares, ay?- ¿Y yo? ¡Del orto!",
      "- ¿Ligás a mares? - Ay, ¿y yo? ¡Del orto!",
      "- ¿Ligás a mares, ay?- ¿Y yo? ¡Del orto!",
      "- ¿Ligás a mares? - Ay, ¿y yo? ¡Del orto!",
      "- ¿Ligás a mares, ay?- ¿Y yo? ¡Del orto!",
      "- ¿Ligás a mares, ala? - ¿Y yo? ¡Del orto!",
      "- ¿Ligás a mares, ala? - ¿Y yo? ¡Del orto!"
    ],
    [
      "A otro cortos asir propone: - Dele,",
      "A otro, cortos asir. Propone: - Dele,",
      "A otro cortos asir, ya pone: - Dele,",
      "A otro, cortos asir. ya pone: - Dele,",
      "A otro, cortos asir, propone. - Dele,",
      "¿A otro cortos asir? Ya pone: - Dele,",
      "¿A otro cortos asir? Propone: - Dele,",
      "¿A otro? Cortos asir, propone: - Dele,",
      "¿A otro, cortos? Asir propone: - Dele,",
      "¿A otro, cortos? ¡Asir! Ya pone: - Dele,"
    ],
    [
      "y ligar falos, ojo. - ¿Y así, rica?",
      "y ligar falos, ojo. - ¿Y así, rica?",
      "y ligar falos, ojo. - ¿Y así, rica?",
      "y ligar falos -ojo- ya. - ¿Sí, rica?",
      "y ligar falos -ojo- ya. - ¿Sí, rica?",
      "y ligar falos -ojo- ya. - ¿Sí, rica?",
      "y ligar falos, ¡ala, ya! - ¿Sí, rica?",
      "y ligar falos, ¡ala! - ¿Y así, rica?",
      "y ligar falos, ¡ala! - ¿Y así, rica?",
      "y ligar falos, ¡ala! - ¿Y así, rica?"
    ],
    [
      "Ya la loca lo note, nos revele",
      "Ya la loca lo note, nos revele",
      "Ya la loca lo rote, nos revele",
      "Ya la loca lo rote, nos revele",
      "Ya la loca le dé la sed, revele",
      "Y a la loca le dé la sed, revele",
      "Ya la loca le dé mi sed, revele",
      "Y a la loca le dé mi sed, revele",
      "Ya la loca mi sí -mi sed- revele",
      "Y a la loca mi sí mi sed revele"
    ],
    [
      "verdad, la musa raya plan, aplica",
      "verdad, la musa a mí salaz aplica",
      "verdad, la musa sé veraz aplica",
      "verdad, la mala raya plan, aplica",
      "verdad, la mala a mi salaz aplica",
      "verdad, la mala sé veraz aplica",
      "verdad, la musa -solo gol- aplica",
      "verdad, la mala -solo gol- aplica",
      "verdad, la mima raya plan, aplica",
      "verdad, la mima -solo gol- aplica"
    ],
    [
      "falo y así revela a ti Sodoma,",
      "falo, revela a ti modo Sodoma,",
      "falo y así revela de Sodoma,",
      "falo, revela arriba de Sodoma,",
      "falo, revela aroma de Sodoma,",
      "falo, revela arriba a ti Sodoma,",
      "falo, revela vida a ti Sodoma,",
      "falos a paranoica de Sodoma,",
      "falo, revélete como Sodoma,",
      "falos, ama, y a ti, modo Sodoma,"
    ],
    [
      "y da, devela, ve una llana broma.",
      "y da, devela di vergel, aroma.",
      "y da, devela ya vergel, aroma.",
      "y da, devela sí le das la broma.",
      "y da, devélate vergel, aroma.",
      "y da, devela losa, oíd la broma.",
      "y da, devela llana barra, broma.",
      "y da del arte por temor a broma.",
      "y da, devela viva llana broma.",
      "y da, devélale vergel, aroma."
    ]
  ]
};
